language: generic
sudo: required

addons:
  apt:
    packages:
    - nginx

script: sudo nginx -t -c nginx.conf -p .

before_deploy:
- openssl aes-256-cbc -K $encrypted_57510f08f3ae_key -iv $encrypted_57510f08f3ae_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master