language: generic
sudo: required
addons:
  apt:
    packages:
    - nginx
  ssh_known_hosts: 119.29.252.110

before_script:
- openssl aes-256-cbc -K $encrypted_06736a13cd4c_key -iv $encrypted_06736a13cd4c_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

script: sudo nginx -t -c nginx.conf -p .

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master

