language: generic
sudo: required
addons:
  apt:
    packages:
    - nginx

before_script:
- openssl aes-256-cbc -K $encrypted_06736a13cd4c_key -iv $encrypted_06736a13cd4c_iv
  -in 2_api.baoleme.andiedie.cn.key.enc -out certificate/2_api.baoleme.andiedie.cn.key
  -d

script: sudo nginx -t -c nginx.conf -p .

before_deploy:
- openssl aes-256-cbc -K $encrypted_06736a13cd4c_key -iv $encrypted_06736a13cd4c_iv
  -in deploy_rsa.enc -out deploy_rsa -d

deploy:
  provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: test

