version: '2'

services:
  api:
    image: node:alpine
    networks:
    - network
    volumes:
    - /root/baoleme/server:/server
    working_dir: /server
    command: npm start
  proxy:
    image: nginx
    networks:
    - network
    volumes:
    - /root/baoleme/nginx:/etc/nginx
    - /root/baoleme/server/files:/files
    ports:
    - 443:443
    links:
    - api

networks:
  network: